baseURL = "https://plafon-pvc.bangunan.co/"
languageCode = "id"
title = "Pasang Plafon PVC | Jual dan Pasang Plafon PVC Berbagai Model Murah"
theme = "saeseen-hugo"
summaryLength = 25
paginate = 6

[permalinks]
  post = "/:slug/"
  page = "/:slug/"
  category = "/:slug/"

[params]
  # Site-wide settings
  meta_description = "Jual Plafon PVC dan Jasa Pasang Plafon - Berpengalaman, Profesional, dan Berkualitas"
  viewport = "width=device-width, initial-scale=1.0"
  fontawesome = "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
  logo = "/images/logo/bangunanco-logo-web.png"
  logo_amp = "/images/logo/bangunanco-512x512.png"
  footer_logo = "/images/logo/bangunanco-logo-putih.png"
  favicon = "/images/logo/bangunanco-512x512.png"
  featured_image = "/images/admin/featured-image.png"
  author = "K. Yaman"
  telepon = "//+6285776786091"
  whatsapp = "//api.whatsapp.com/send?phone=6285776786091&text=*Halo bangunan.co*%20%3A"
  enableWhatApps = true
  enableTelepon = true
  tocMinWordCount = 300
  tableOfContent = "Daftar Isi:"
  geo_latitude = -6.595038
  geo_longitude = 106.817787
  opening_hours = "Mo-Sa 08:00-17:00"

  # Schema settings
  keywords = ["jual plafon pvc", "pasang plafon pvc", "model plafon pvc", "plafon pvc murah", "plafon ruang tamu pvc", "plafon kamar tidur pvc"]
  base_price = 50000
  price_range = 25000
  free_consultation = true
  service_types = [
  "Pasang Plafon PVC Ruang Tamu",
  "Pasang Plafon PVC Kamar Tidur",
  "Pasang Plafon PVC Dapur",
  "Pasang Plafon PVC Anti Air",
  "Pasang Plafon PVC Seluruh Rumah"
  ]
  categories = ["Jasa Pasang Plafon PVC", "Plafon PVC", "Plafon Rumah"]
  payment_methods = ["Bayar Bertahap", "Transfer Bank", "Bayar DP 50%", "Transfer Setelah Selesai"]
  cancellation_policies = [
  "Layanan dapat dibatalkan jika hasil pemasangan tidak sesuai dengan kesepakatan.",
  "Pengembalian biaya jika hasil pemasangan tidak memuaskan.",
  "Revisi gratis jika pemasangan tidak rapih atau sesuai harapan."
  ]
  area_served = ["Jakarta", "Bogor", "Depok", "Tangerang", "Bekasi", "Cikarang", "Karawang", "Bandung", "Purwakarta", "Serang", "Cikampek", "Subang"]
  service_output = "Ruangan dengan plafon PVC yang terpasang rapi dan sesuai permintaan."

 # Hero Section
  hero_image = "/images/admin/bg_bangunanco.png"
  hero_title = "Jasa Pasang Plafon PVC Profesional"
  hero_description = "Kami menawarkan berbagai pilihan plafon PVC berkualitas, dengan desain modern dan material tahan lama. Solusi terbaik untuk memperindah dan melindungi interior rumah atau kantor Anda dengan pemasangan yang rapi dan profesional."
  hero_cta_text = "Pelajari Lebih Lanjut"
  services_cta_text = "Cek Katalog Plafon PVC"

# Footer Section
  footer_about_title = "Mengapa Memilih Kami"
  footer_about_description = "Kami menyediakan layanan pasang plafon PVC profesional dengan berbagai pilihan desain, bahan berkualitas, dan harga terjangkau. Layanan pengukuran dan pemasangan serta konsultasi gratis untuk membantu Anda menemukan pilihan terbaik."
  footer_services_title = "Kenapa Pilih Kami"
  footer_contact_title = "Kontak Kami"
  footer_bottom_text = "@2024 Bangunan.co. Semua Hak Dilindungi."

  # Testimonials Section
  testimonials_title = "Apa Kata Klien Kami"

  [[params.footer_services]]
  text = "plafon-pvc.bangunan.co menawarkan berbagai pilihan plafon PVC berkualitas dengan desain modern dan material yang tahan lama. Kami mengutamakan kepuasan pelanggan dengan pemasangan plafon yang rapi, cepat, dan profesional. Pilih kami untuk mempercantik dan melindungi rumah atau kantor Anda dengan plafon PVC yang fungsional dan estetis."

  [[params.footer_contact]]
    icon = "fas fa-map-marker-alt"
    text = "Jalan Lkr. Dramaga No. 09, Bogor - JaBar"
  [[params.footer_contact]]
    icon = "fas fa-phone-alt"
    text = "+62 857-7678-6091"
  [[params.footer_contact]]
    icon = "fas fa-envelope"
    text = "bangunanco@gmail.com"

[[params.testimonials]]
  avatar = "/images/admin/avatar1.png"
  name = "{Budi|Joko|Andi|Eko|Rudi|Fajar|Hendra|Samsul|Agus|Dedi}"
  message = "{Saya memasang plafon PVC dari plafon-pvc.bangunan.co di rumah saya, dan hasilnya {sangat memuaskan|luar biasa|menakjubkan}. Kualitasnya {bagus|berkualitas tinggi|premium} dan pemasangannya {rapi|baik|terorganisir}.|Plafon PVC dari plafon-pvc.bangunan.co {sangat memuaskan|berkualitas tinggi|rapi} dan sesuai dengan {desain|konsep|gaya} rumah saya.}"
  response = "{Terima kasih atas {kepercayaannya|pilihan Anda}! Kami senang dapat {menyediakan|menghadirkan} plafon PVC berkualitas untuk {rumah|proyek} Anda.|Kami {menghargai|berterima kasih atas} kepercayaan Anda. Senang dapat {melayani|membantu} Anda dengan produk terbaik.}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar2.png"
  name = "{Siti|Dewi|Rina|Maya|Lina|Sari|Fitri|Nur|Diah|Ayu}"
  message = "{plafon-pvc.bangunan.co {sangat membantu|mempermudah|menyediakan} dalam melengkapi {interior|dekorasi|desain} rumah saya. Plafon PVC yang {saya pilih|saya beli} {sangat berkualitas|premium|bermutu} dan {pas|cocok|ideal} dengan desain interior saya.|Saya terbantu oleh plafon-pvc.bangunan.co dalam memilih plafon PVC untuk {rumah|interior} saya. Kualitasnya {baik|tinggi|premium} dan sesuai dengan {konsep|desain} yang saya inginkan.}"
  response = "{Kami sangat menghargai ulasan Anda. {Senang mendengar|Bahagia mengetahui} bahwa Anda puas dengan layanan dan produk kami.|Terima kasih atas ulasannya! Kami gembira Anda puas dengan hasilnya.}"
  rating = 5

[[params.testimonials]]
  avatar = "/images/admin/avatar3.png"
  name = "{Joko|Bambang|Hadi|Tono|Gilang|Bayu|Faisal|Rizal|Ali|Ahmad}"
  message = "{Plafon PVC dari plafon-pvc.bangunan.co {sangat estetis|indah|menawan} dan cocok untuk {ruang tamu|ruangan|interior} saya. Proses pemasangan juga {sangat cepat|cepat|tepat waktu} dan profesional.|Saya {sangat puas|terkesan|senang} dengan plafon PVC dari plafon-pvc.bangunan.co. Desainnya {estetis|indah|minimalis} dan pemasangannya {profesional|rapi|cepat}.}"
  response = "{Terima kasih! Kami {berkomitmen|fokus|dedikasi} untuk menyediakan plafon PVC yang {fungsional|estetis|berkualitas}.|Kami {senang|gembira} dapat membantu Anda dengan plafon PVC berkualitas. Terima kasih atas ulasannya!}"
  rating = 4

[[params.testimonials]]
  avatar = "/images/admin/avatar4.png"
  name = "{Andi|Bayu|Fajar|Hendra|Dian|Rizky|Yoga|Yudi|Ari|Gani}"
  message = "{Saya {sangat puas|senang|terkesan} dengan pemasangan plafon PVC dari plafon-pvc.bangunan.co. Plafon tersebut {sangat sesuai|pas|cocok} dengan desain minimalis yang saya inginkan.|Pemasangan plafon PVC dari plafon-pvc.bangunan.co {sangat rapi|cepat|profesional} dan sesuai dengan konsep desain saya.}"
  response = "{Senang mendengar Anda puas dengan produk dan layanan kami. Terima kasih atas {kepercayaannya|pilihan Anda}!|Kami {berterima kasih|menghargai} atas kepercayaan Anda. Senang mendengar proyek Anda berjalan dengan baik!}"
  rating = 4.5

[[params.testimonials]]
  avatar = "/images/admin/avatar5.png"
  name = "{Rina|Siti|Dewi|Lina|Ayu|Fitri|Sari|Diah|Nur|Maya}"
  message = "{Pelayanan plafon-pvc.bangunan.co {sangat memuaskan|luar biasa|terbaik}. Plafon PVC yang saya {pasang|gunakan} di kantor {sangat berkualitas|bermutu tinggi|premium} dan sesuai dengan {harapan saya|ekspektasi saya|standar yang saya butuhkan}.|Saya {sangat puas|terkesan|senang} dengan pelayanan dari plafon-pvc.bangunan.co. Plafon PVC yang saya {beli|gunakan} {sangat berkualitas|bermutu tinggi|premium} dan {sesuai|ideal} dengan harapan saya.}"
  response = "{Terima kasih! Kami senang dapat {membantu|melayani|memenuhi kebutuhan} proyek kantor Anda dengan {plafon PVC terbaik|produk berkualitas}.|Kami sangat menghargai ulasan Anda. Terima kasih telah {memilih|mempercayai|menggunakan} produk kami!}"
  rating = 4.8

[[params.testimonials]]
  avatar = "/images/admin/avatar6.png"
  name = "{Eko|Agus|Dedi|Toni|Yanto|Wawan|Benny|Rio|Iwan|Galih}"
  message = "{Plafon PVC dari plafon-pvc.bangunan.co {sangat sesuai|tepat|cocok} dengan desain interior rumah saya. Pemasangannya juga {cepat|rapi|profesional} dan sangat {baik|teratur|tepat}.|Saya {senang|puas|terkesan} dengan produk plafon PVC dari plafon-pvc.bangunan.co. Desainnya {sesuai|ideal} dan pemasangannya {cepat|profesional|rapi}.}"
  response = "{Kami {senang|bahagia|gembira} mendengar bahwa Anda puas dengan {produk|layanan} kami. Terima kasih atas {ulasannya|kepercayaannya}!|Terima kasih telah {memilih|mempercayai|menggunakan} produk kami. Kami {gembira|senang} Anda puas dengan hasilnya.}"
  rating = 5

[[params.tabelItems]]
  name = "Pasang Plafon PVC Ruang Tamu"
  price = "250.000 /m"
[[params.tabelItems]]
  name = "Pasang Plafon PVC Kamar Tidur"
  price = "270.000 /m"
[[params.tabelItems]]
  name = "Pasang Plafon PVC Dapur"
  price = "250.000 /m"
[[params.tabelItems]]
  name = "Pasang Plafon PVC Anti Air"
  price = "350.000 /m"
[[params.tabelItems]]
  name = "Pasang Plafon PVC Seluruh Rumah"
  price = "230.000 /m"

[params.appliList]
  "Pasang Plafon PVC Ruang Tamu" = "ruang tamu, ruang keluarga, ruang tamu modern"
  "Pasang Plafon PVC Kamar Tidur" = "kamar tidur utama, kamar anak"
  "Pasang Plafon PVC Dapur" = "dapur rumah, area memasak"
  "Pasang Plafon PVC Anti Air" = "kamar mandi, area lembap"
  "Pasang Plafon PVC Seluruh Rumah" = "plafon seluruh rumah atau bangunan"

[params.kegunaanList]
  "Pasang Plafon PVC Ruang Tamu" = "menciptakan tampilan elegan dan modern di ruang tamu"
  "Pasang Plafon PVC Kamar Tidur" = "memberikan kenyamanan dan tampilan rapi di kamar tidur"
  "Pasang Plafon PVC Dapur" = "melindungi area dapur dari kelembapan dan mempercantik ruangan"
  "Pasang Plafon PVC Anti Air" = "tahan air, cocok untuk area lembap seperti kamar mandi"
  "Pasang Plafon PVC Seluruh Rumah" = "menyelaraskan desain plafon di seluruh ruangan rumah"

  # Menu Section
  [[params.menu_items]]
    title = "Beranda"
    url = "/"
  [[params.menu_items]]
    title = "Profile"
    url = "https://bangunan.co/profile/"
  [[params.menu_items]]
    title = "Daftar Harga"
    url = "https://bangunan.co/daftar-harga/"

[params.header]
   title = "Jasa Pasang dan Penjualan Plafon PVC Berkualitas | "
   highlight = "Bangunan.co"

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 3

[related]
  threshold = 80
  includeNewer = true
  toLower = false

[[related.indices]]
  name = "categories"
  weight = 100

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "AMP"]

[outputFormats]
  [outputFormats.AMP]
    mediaType = "text/html"
    baseName = "amp/index"
    path = ""
    isPlainText = false
    permalinkable = true
    rel = "amphtml"